[package]
name = "trogue"
version = "0.1.0"
authors = ["LucasGobbs <llcostagobbi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetra = "0.4.0"
itertools = "0.9.0"
rand = "0.7"
regex = "1"